---
# control
control:
  num_supervised: '4000'
  loss_mode: 'fix@0.95-mix'
  num_clients: '15'
  active_rate: '0.2'
  data_split_mode: 'iid'
  local_epoch: '5-5'
  gm: '0.2'
  sbn: '0'
  ft: '1'
  switch_epoch : 0
# data
data_name: office31
data_name_unsup : office31
model_name: resnet18
# experiment
num_supervised_clients: 5
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
threshold : .8
verbose: False
switch_epoch : 0
cycles : 200
d_mode : 'new'
switch_epoch_pred : 0
kl_loss : 0
elr_lam : 1.0
var_lr : 0.001
scheduler_name : 'ExponentialLR'
DA : 1
domain_s : 'dslr'
domain_u : 'amazon'
# unsup_list : ['amazon','webcam']
unsup_list : ["amazon"]
unsup_doms : 'amazon-webcam'
test_10_crop : False
bt : 50
adapt_wt : 0
avg_cent : 0
avg_cent_alpha: 0.5
backbone_arch : 'resnet50'
embed_feat_dim : 256
tde : 5
pre_trained : 1
gamma : 0.1
decay : 0.9
par : 0
tau : 0.5
kl : 0
kl_weight : 0.1
new_lr : 0
unsup_mode : 'bmd'
# SYN32 dataset
# Max limit for total dataset size
syn_max_train: 50000
# Activation-norm/std for each layer
compute_mean_norm: True
compute_std_dev: False
compute_running_mean: True
compute_running_var: True
mean_norm_reg: 0.01
std_dev_reg: 0
running_mean : 0
running_var : 0
wt_actloss : 0.01
add_fix : 0
full_sup : 0
with_BN : 1
train_pass : 0
module_name : None
register_hook_BN : 0