# control
control:
  num_supervised: '4000'
  loss_mode: 'fix@0.95-mix'
  num_clients: '15'
  active_rate: '0.2'
  data_split_mode: 'iid'
  local_epoch: '5-5'
  gm: '0.2'
  sbn: '0'
  ft: '1'
  switch_epoch : 0
# data
# data_name: 'OfficeHome'
# data_name_unsup : 'OfficeHome'
data_name: 'office31'
data_name_unsup : 'office31'
model_name: resnet18
# experiment
num_supervised_clients: 5
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
resume_mode_target: 0
threshold : .8
verbose: False
switch_epoch : 0
cycles : 200
d_mode : 'new'
switch_epoch_pred : 0
kl_loss : 0
elr_lam : 1.0
var_lr : 0.001
scheduler_name : 'ExponentialLR'
DA : 1
domain_s : 'dslr'
domain_u : 'amazon'
# unsup_list : ['amazon' 'webcam']
unsup_list : ["amazon"]
unsup_doms : 'amazon-webcam'
test_10_crop : False
bt : 50
adapt_wt : 0
avg_cent : 0
avg_cent_alpha: 0.5
backbone_arch : 'resnet50'
embed_feat_dim : 256
tde : 5
pre_trained : 1
gamma : 0.1
decay : 0.9
par : 0
tau : 0.5
kl : 0
kl_weight : 0.1
new_lr : 0
unsup_mode : 'bmd'
# SYN32 dataset
# Max limit for total dataset size
syn_max_train: 50000
# Activation-norm/std for each layer
compute_mean_norm: True
compute_std_dev: False
compute_running_mean: True
compute_running_var: True
mean_norm_reg: 0.01
std_dev_reg: 0
running_mean : 0
running_var : 0
wt_actloss : 0.00
add_fix : 0
full_sup : 0
with_BN : 1
train_pass : 0
module_name : None
register_hook_BN : 0
post_conv : 0
num_sup : 0
run_shot : 1
temp : 8.0
wt_avg : 1
pretrained_source : 0
tag_ : None
loss_mse : 0
kl_loss : 0
multi_model : 0
client_test : 0
trk_grad : 0 
pick : 'best'
lambda : 1.0
cent_log : 1
save_cent : 0
logit_div : 0
cluster : 0
save_epoch : 0

#####crco
baseline_type : 'IM' 
lambda_ent : 1.0
lambda_div : 1.0 
lambda_aad : 1.0  
fix_classifier : True 
prob_threshold : 0.95 
feat_dim : 256 
pseudo_update_interval : 100000  
threshold_crco : 0.0
num_k : 4  
num_m : 3  
lambda_near : 0.0 
lambda_fixmatch : 0.0  
fixmatch_start : 0  
fixmatch_type : 'class_relation' 
use_cluster_label_for_fixmatch : False 
lambda_fixmatch_temp : 0.07 
bank_size : 512  
lambda_nce : 1.0 
lambda_temp : 0.07 
non_diag_alpha : 1.0  
add_current_data_for_instance : False 
use_only_current_batch_for_instance : False  
max_iters : 15000  
beta : 0.0 
#################################################
#add mix_up loss
new_mix : 0
lam : 0.5
vit_bn : False
var_reg : False
global_reg : 0
g_lambda : 1.0
var_wt : 0.1
clip_t : 0
cls_ps : False
svd_plot : False
run_crco : 0
GD : 0
den_plot_mode : FedSFDAsingle_combined
add_ln : 0
plt_hist : 0
adpt_thr : 0
labels_count : 0
FedProx : 0
mu : 0.01
shot3x : 0
add3x : 0
only_bn : 0 
run_hcld : 0
run_UCon: 0