---
# control
control:
  num_supervised: '4000'
  loss_mode: 'fix@0.95-mix'
  num_clients: '100'
  active_rate: '0.1'
  data_split_mode: 'iid'
  local_epoch: '5-5'
  gm: '0.2'
  sbn: '0'
  ft: '1'
  switch_epoch : 0
# data
data_name: CIFAR10
model_name: resnet18
# experiment
num_supervised_clients: '10'
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
threshold : .8
verbose: False
switch_epoch : 0
cycles : 200
d_mode : 'new'
switch_epoch_pred : 0